### ISSUE TITLE
Projeto em Desenvolvimento

### ISSUE THREAD

**Issue by kleyton032** [vitorsilv/first-tdd#1]
Olá, estou atrás de caras devs que queiram aprofundar o seu aprendizado(assim com eu), por um acaso achei teu Github, e vi que você movimenta ele recentemente, e estais estudando muito da Stack node e mongo, Estou criando um mini ERP com essas tecnologias e outras a mais, e gostaria de saber se tens interesse em programar algumas horas cmg nessa jornada hehehe.

**Comment by vitorsilv** [comment]
Olá @kleyton032 
Tento me fazer esses testes com o tempo que me sobra, mas acredito que por agora não consiga ajudar muito com o esse projeto do mini ERP. Achei muito interessante a proposta, fiquei bem curioso, mas já estou envolvido em outros projetos então o problema é realmente o tempo.

Agradeço pelo contato, caso meus horários mudem volto a falar contigo, muita sorte neste projeto!
